sudo: required
services:
  - docker

before_install:
  - docker build -t dockeryt -f Dockerfile.dev .

script: 
  - docker run -e CI=true dockeryt npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "docker-youtube"
  env: "Dockeryoutube-env"
  bucket_name: "elasticbeanstalk-us-east-1-563684797122"
  bucket_path: "docker-youtube"
  on:
    branch: main
